<a href="https://colab.research.google.com/github/Mal-Lem/Pandas-pour-DS/blob/main/3_data_cleaning_avec_pandas_Exercice_%C3%A9l%C3%A8ve_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Exercice 1 </h1>

On vous a donné un ensemble de données nécessitant un nettoyage avant l'analyse.

Le DataFrame df contient des informations sur des employés, y compris leur catégorie de travail, leur salaire, leur âge, le nombre de visites et leur évaluation.

Avec le DataFrame df fourni, effectuez les tâches suivantes de nettoyage de données :

1) Affichez les cinq premières et les cinq dernières lignes du DataFrame.
2) Obtenez le nombre total de lignes, la taille totale du DataFrame et sa forme.
3) Utilisez describe() pour obtenir un résumé statistique du DataFrame.
4) Réordonnez les colonnes en plaçant 'Employee' comme première colonne.
5) Renommez la colonne 'Category' en 'Department'.
6) Affichez les informations générales du DataFrame avec .info().
7) Vérifiez les types de données de chaque colonne avec dtypes et convertissez la colonne 'Salary' en type numérique.
8) Gérez les valeurs manquantes : identifiez-les, comptez-les, supprimez les lignes avec des valeurs manquantes dans 'Employee', et remplacez les valeurs manquantes dans 'Age' par la médiane.
9) Identifiez et supprimez les lignes en double, en gardant la première occurrence.
10) Remplacez toutes les occurrences de 'not available' dans 'Salary' par NaN.
11) Séparez la colonne 'Date' en deux colonnes distinctes 'Year' et 'Month' en utilisant .split('-').
12) Utilisez .apply() pour créer une nouvelle colonne 'Seniority' basée sur l'âge de l'employé : "Senior" pour plus de 40 ans, "Junior" pour moins.
13) Réinitialisez l'index.
14) Affichez le résumé final de .info() pour le DataFrame nettoyé.

In [36]:
import pandas as pd

df = pd.read_csv('employes.csv')

In [37]:
#1. Afficher les premières et dernières lignes
df.head()
df[-5:]

          Date Category Employee     Salary   Age  Visits  Rating
28  2023-01-29      NaN    Frank   86529.38   NaN       0    3.21
29  2023-01-30   Health    Heidi   79026.34  45.0      50    1.66
30  2023-01-01  Finance    Frank   88416.95  40.0      42    3.69
31  2023-01-02   Health      Bob  100063.26  40.0      84    4.89
32         NaN  Finance    Frank   92193.44  35.0      75    4.51

In [38]:
# 2. Nombre de lignes, taille et forme
df.shape

(33, 7)

In [39]:
# 3. Résumé statistique
df.describe()

             Age     Visits     Rating
count  30.000000  33.000000  33.000000
mean   35.333333  54.727273   3.291515
std     6.814454  28.318802   1.249683
min    25.000000   0.000000   1.040000
25%    30.000000  41.000000   2.440000
50%    35.000000  58.000000   3.260000
75%    40.000000  76.000000   4.510000
max    45.000000  99.000000   4.920000

In [40]:
# 4. Réordonner les colonnes
df = df[['Employee', 'Category', 'Salary', 'Age', 'Visits','Date', 'Rating']]
df.head()

  Employee Category     Salary   Age  Visits        Date  Rating
0    Frank  Finance   88416.95  40.0      42  2023-01-01    3.69
1      Bob   Health  100063.26  40.0      84  2023-01-02    4.89
2    Frank  Finance   92193.44  35.0      75  2023-01-03    4.51
3      NaN  Finance   88141.82  45.0      68  2023-01-04    3.04
4    Alice   Health   79655.84  35.0       6  2023-01-05    1.22

In [41]:
# 5. Renommer la colonne
df = df.rename(columns={'Category': 'Department'})
df.head()

  Employee Department     Salary   Age  Visits        Date  Rating
0    Frank    Finance   88416.95  40.0      42  2023-01-01    3.69
1      Bob     Health  100063.26  40.0      84  2023-01-02    4.89
2    Frank    Finance   92193.44  35.0      75  2023-01-03    4.51
3      NaN    Finance   88141.82  45.0      68  2023-01-04    3.04
4    Alice     Health   79655.84  35.0       6  2023-01-05    1.22

In [42]:
# 6. Informations générales
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    23 non-null     object
 1   Department  27 non-null     object
 2   Salary      33 non-null     object
 3   Age         30 non-null     float64
 4   Visits      33 non-null     int64
 5   Date        32 non-null     object
 6   Rating      33 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.9+ KB

In [43]:
#7 Vérifiez les types de données de chaque colonne avec dtypes et convertissez la colonne 'Salary' en type numérique
df.dtypes
df.Salary = pd.to_numeric(df.Salary, errors = 'coerce')
df.dtypes

Employee       object
Department     object
Salary        float64
Age           float64
Visits          int64
Date           object
Rating        float64
dtype: object

In [44]:
# 8. Gestion des valeurs manquantes
df.isnull().sum()
df.dropna(subset=['Employee'], inplace=True)
df.Age.fillna(df.Age.median(), inplace=True)
df.isnull().sum()

<ipython-input-44-0f8374982863>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(df.Age.median(), inplace=True)

Employee      0
Department    4
Salary        5
Age           0
Visits        0
Date          1
Rating        0
dtype: int64

In [45]:
# 9. Gestion des doublons
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [46]:
# 10. Remplacer 'not available' par NaN
df.Salary.replace('not available', pd.NA, inplace=True)
df.Salary

<ipython-input-46-259aa2ed9fdd>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Salary.replace('not available', pd.NA, inplace=True)

0      88416.95
1     100063.26
2      92193.44
4      79655.84
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16     51415.29
18    104470.97
19    110900.85
20    118503.28
21    105941.10
24     58279.21
25     94794.47
26     60034.73
27    116126.82
28     86529.38
29     79026.34
32     92193.44
Name: Salary, dtype: float64

In [52]:
# 11. Séparer la date
df[['Year', 'Month']] = df.Date.str.split('-', expand=True,n=1)
df.head()

,Employee,Department,Salary,Age,Visits,Date,Rating,Year,Month
0,Frank,Finance,88416.95,40.0,42,2023-01-01,3.69,2023,01-01
1,Bob,Health,100063.26,40.0,84,2023-01-02,4.89,2023,01-02
2,Frank,Finance,92193.44,35.0,75,2023-01-03,4.51,2023,01-03
4,Alice,Health,79655.84,35.0,6,2023-01-05,1.22,2023,01-05
11,Alice,Finance,NaN,45.0,15,2023-01-12,3.75,2023,01-12

In [53]:
# 12. Appliquer une fonction pour créer une nouvelle colonne
df['Seniority'] = df.Age.apply(lambda x: 'Senior' if x > 40 else 'Junior')
df.head()

,Employee,Department,Salary,Age,Visits,Date,Rating,Year,Month,Seniority
0,Frank,Finance,88416.95,40.0,42,2023-01-01,3.69,2023,01-01,Junior
1,Bob,Health,100063.26,40.0,84,2023-01-02,4.89,2023,01-02,Junior
2,Frank,Finance,92193.44,35.0,75,2023-01-03,4.51,2023,01-03,Junior
4,Alice,Health,79655.84,35.0,6,2023-01-05,1.22,2023,01-05,Junior
11,Alice,Finance,NaN,45.0,15,2023-01-12,3.75,2023,01-12,Senior

In [54]:
# 13. Réinitialiser l'index
df.reset_index(drop=True, inplace=True)
df.head()

,Employee,Department,Salary,Age,Visits,Date,Rating,Year,Month,Seniority
0,Frank,Finance,88416.95,40.0,42,2023-01-01,3.69,2023,01-01,Junior
1,Bob,Health,100063.26,40.0,84,2023-01-02,4.89,2023,01-02,Junior
2,Frank,Finance,92193.44,35.0,75,2023-01-03,4.51,2023,01-03,Junior
3,Alice,Health,79655.84,35.0,6,2023-01-05,1.22,2023,01-05,Junior
4,Alice,Finance,NaN,45.0,15,2023-01-12,3.75,2023,01-12,Senior

In [55]:
#14 info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    21 non-null     object
 1   Department  17 non-null     object
 2   Salary      16 non-null     float64
 3   Age         21 non-null     float64
 4   Visits      21 non-null     int64
 5   Date        20 non-null     object
 6   Rating      21 non-null     float64
 7   Year        20 non-null     object
 8   Month       20 non-null     object
 9   Seniority   21 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 1.8+ KB